### ISSUE TITLE
Mod behaves weirdly on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [DakotaPride/Incantation#1]
https://pastebin.com/izD06Jgg

**Comment by DakotaPride** [comment]
That is due to this mod being designed for Fabric and not Quilt. Even though Quilt and Fabric are similar to my knowledge, they are still different and cannot be expected to behave the exact same. I do not currently have plans to port this mod over to Quilt, though that could change in the future. If you have any more questions, please feel free to let me know!

**Comment by acikek** [comment]
No, it's because before you fixed it, Fabric API version was set to an exact match with the `=` operator. This should run perfectly fine on Quilt.

**Comment by Sunconure11** [comment]
@DakotaPride Might want to see this.

**Comment by DakotaPride** [comment]
I'm still not entirely sure what I can do to fix this, as when I attempt to use Quilt (with More Weaponry/Incantation installed) it works just fine. The person above unfortunately doesn't specify where exactly this happens (Fabric API Version specified in gradle.properties seems fine. I will try to mess around with some values (such as updating or downgrading fabric for example) to see if that will potentially work. Though, I don't plan to release v0.1.4 just yet, as it's not entirely ready for beta release #2.
@Sunconure11 

As a side note, is the Pastebin you provided meant to be a crash report or simply your latest.log file? While the latest.log file is helpful, it doesn't always mean that there is something wrong with the mod. (for example, the SemVer error is due to the 'weird' formatting of the mod_version in gradle.properties)

**Comment by Sunconure11** [comment]
Latest.log, because I couldn't generate a crash due to other reasons

**Comment by Sunconure11** [comment]
![Untitled](https://user-images.githubusercontent.com/5614902/179383071-7dbf2624-8888-479a-a74c-c6d89ba129c4.png)

Only issue I have with the mod now is this.

**Comment by DakotaPride** [comment]
@Sunconure11 
Okay, thank you for providing all of this information. Please know that in the next release for both mods, you will be able to use them with most any fabric API, as well as the mods will be updated to the newest fabric API/Loader versions for 1.19. Thank you for your patience with this issue! (Both mod versions should be released sometime within the next few days)

**Comment by DakotaPride** [comment]
@Sunconure11 
Issue Should Now Be Resolved In [Incantation v0.1.4](https://www.curseforge.com/minecraft/mc-mods/incantation/files/3879823)
