### ISSUE TITLE
Newer version of Fabric is incompatible?

### ISSUE THREAD

**Issue by jaredniegas** [DakotaPride/Incantation#2]
When I try playing with the mod, a warning tells me my version of Fabric isn't the right one.

**Comment by DakotaPride** [comment]
As of right now, Incantation requires that you use Fabric API version 0.55.3 for 1.19. In a later version, this shouldn't be an issue however, and you should be able to use API versions past 0.55.3. As for using Fabric API 0.55.3 instead of the newest version as of Incantation v0.1.3, this was a mistake that I made on my end, not releasing that Fabric had created a newer version as of release. Again, in the next Incantation version (v0.1.4) you should be able to play with Incantation installed no matter the API version. This update will be half/half a content update as well as a patch, so if there are any other bugs/issues that you come across, feel free to open an issue!
@jaredniegas

**Comment by DakotaPride** [comment]
@jaredniegas 
Issue Should Now Be Resolved In [Incantation v0.1.4](https://www.curseforge.com/minecraft/mc-mods/incantation/files/3879823)

**Comment by jaredniegas** [comment]
> 

Thank you! I have the mod working now. :)
